version: '3.7'

services:
  bot-reativacao:
    image: bot-reativacao-vet:latest

    networks:
      - talkhub

    environment:
      - PORT=2080
      - NODE_ENV=production
      - TZ=America/Sao_Paulo

    env_file:
      - .env

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:2080/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.role == manager

      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M

      labels:
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.docker.network=talkhub"

        # CRITICAL: Define the service FIRST
        - "traefik.http.services.bot-reativacao-svc.loadbalancer.server.port=2080"

        # HTTP Router (redirect to HTTPS)
        - "traefik.http.routers.bot-reativacao-http.rule=Host(`automacaobs.talkhub.me`)"
        - "traefik.http.routers.bot-reativacao-http.entrypoints=web"
        - "traefik.http.routers.bot-reativacao-http.middlewares=https-redirect"

        # HTTPS Router - CONNECTED TO SERVICE
        - "traefik.http.routers.bot-reativacao-https.rule=Host(`automacaobs.talkhub.me`)"
        - "traefik.http.routers.bot-reativacao-https.entrypoints=websecure"
        - "traefik.http.routers.bot-reativacao-https.tls=true"
        - "traefik.http.routers.bot-reativacao-https.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.bot-reativacao-https.service=bot-reativacao-svc"

        # HTTPS Redirect Middleware
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  talkhub:
    external: true
